name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t adityopratama/flutter-melos:2.8.1 .
      - name: Push image
        run: docker push adityopratama/flutter-melos:2.8.1
